/-
Copyright (c) 2025 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import BrownianMotion.StochasticIntegral.ClassD
public import Mathlib.Topology.EMetricSpace.BoundedVariation

/-! # Doob-Meyer decomposition theorem

-/

@[expose] public section

open MeasureTheory Filter TopologicalSpace
open scoped ENNReal

namespace ProbabilityTheory

variable {ι Ω : Type*} [LinearOrder ι] [OrderBot ι] [TopologicalSpace ι] [OrderTopology ι]
  {mΩ : MeasurableSpace Ω} {P : Measure Ω} {X : ι → Ω → ℝ} {𝓕 : Filtration ι mΩ}
  [MeasurableSpace ι]

omit [TopologicalSpace ι] [OrderTopology ι] [MeasurableSpace ι] in
/-- Adding an integrable `𝓕_⊥`-measurable random variable as a time-constant process preserves
the martingale property.  This is the non-local closure fact needed after localization in the
normalized Doob-Meyer proof. -/
lemma _root_.MeasureTheory.Martingale.add_const_fun [SigmaFiniteFiltration P 𝓕]
    {M : ι → Ω → ℝ} {Z : Ω → ℝ} (hM : Martingale M 𝓕 P)
    (hZ_meas : StronglyMeasurable[𝓕 ⊥] Z) (hZ_int : Integrable Z P) :
    Martingale (M + fun _ ↦ Z) 𝓕 P := by
  exact hM.add (martingale_const_fun 𝓕 P hZ_meas hZ_int)

omit [TopologicalSpace ι] [OrderTopology ι] [MeasurableSpace ι] in
/-- A time-constant process generated by an `𝓕_⊥`-measurable random variable is strongly
predictable. -/
lemma _root_.MeasureTheory.IsStronglyPredictable.const_fun {Z : Ω → ℝ}
    (hZ : StronglyMeasurable[𝓕 ⊥] Z) :
    IsStronglyPredictable 𝓕 (fun _ : ι => Z) := by
  rw [MeasureTheory.IsStronglyPredictable]
  rw [stronglyMeasurable_iff_measurable]
  have hsnd : @Measurable (ι × Ω) Ω 𝓕.predictable (𝓕 ⊥) Prod.snd := by
    rw [measurable_iff_comap_le, MeasurableSpace.comap_le_iff_le_map]
    intro s hs
    rw [MeasurableSpace.map_def]
    have hpre : Prod.snd ⁻¹' s = (Set.univ : Set ι) ×ˢ s := by
      ext p
      simp
    rw [hpre]
    exact MeasureTheory.measurableSet_predictable_univ_prod (𝓕 := 𝓕) hs
  simpa [Function.uncurry] using hZ.measurable.comp hsnd

omit [TopologicalSpace ι] [OrderTopology ι] [MeasurableSpace ι] in
/-- Strong predictability is stable under subtracting real-valued processes. -/
lemma _root_.MeasureTheory.IsStronglyPredictable.sub {U V : ι → Ω → ℝ}
    (hU : IsStronglyPredictable 𝓕 U) (hV : IsStronglyPredictable 𝓕 V) :
    IsStronglyPredictable 𝓕 (U - V) := by
  rw [MeasureTheory.IsStronglyPredictable] at hU hV ⊢
  simpa [Function.uncurry, Pi.sub_apply] using hU.sub hV

omit [OrderBot ι] [TopologicalSpace ι] [OrderTopology ι] [MeasurableSpace ι] in
/-- Real-valued bounded-variation functions are stable under subtraction. -/
lemma _root_.BoundedVariationOn.sub {f g : ι → ℝ} {s : Set ι}
    (hf : BoundedVariationOn f s) (hg : BoundedVariationOn g s) :
    BoundedVariationOn (f - g) s := by
  have hle : eVariationOn (f - g) s ≤ eVariationOn f s + eVariationOn g s := by
    rw [eVariationOn]
    refine iSup_le ?_
    rintro ⟨n, u, hu, hus⟩
    calc
      (∑ i ∈ Finset.range n,
          edist ((f - g) (u (i + 1))) ((f - g) (u i)))
          ≤ ∑ i ∈ Finset.range n,
              (edist (f (u (i + 1))) (f (u i)) +
                edist (g (u (i + 1))) (g (u i))) := by
            refine Finset.sum_le_sum fun i _ ↦ ?_
            simp only [Pi.sub_apply]
            calc
              edist (f (u (i + 1)) - g (u (i + 1))) (f (u i) - g (u i))
                  ≤ edist (f (u (i + 1)) - g (u (i + 1)))
                      (f (u i) - g (u (i + 1))) +
                    edist (f (u i) - g (u (i + 1))) (f (u i) - g (u i)) :=
                    edist_triangle _ _ _
              _ = edist (f (u (i + 1))) (f (u i)) +
                    edist (g (u (i + 1))) (g (u i)) := by
                    rw [edist_sub_right, edist_sub_left]
      _ = (∑ i ∈ Finset.range n, edist (f (u (i + 1))) (f (u i))) +
            ∑ i ∈ Finset.range n, edist (g (u (i + 1))) (g (u i)) := by
          rw [Finset.sum_add_distrib]
      _ ≤ eVariationOn f s + eVariationOn g s := by
          exact add_le_add (eVariationOn.sum_le hu hus) (eVariationOn.sum_le hu hus)
  exact ne_top_of_le_ne_top (ENNReal.add_ne_top.2 ⟨hf, hg⟩) hle

omit [OrderBot ι] [TopologicalSpace ι] [OrderTopology ι] [MeasurableSpace ι] in
/-- Locally bounded variation is stable under subtraction for real-valued paths. -/
lemma _root_.LocallyBoundedVariationOn.sub {f g : ι → ℝ} {s : Set ι}
    (hf : LocallyBoundedVariationOn f s) (hg : LocallyBoundedVariationOn g s) :
    LocallyBoundedVariationOn (f - g) s := by
  intro a b ha hb
  exact (hf a b ha hb).sub (hg a b ha hb)

omit [OrderBot ι] [TopologicalSpace ι] [OrderTopology ι] [MeasurableSpace ι] in
/-- Pathwise running-sup estimate for subtracting a time-constant random variable. -/
lemma runningSup_norm_sub_const_le (A : ι → Ω → ℝ) (Z : Ω → ℝ) (t : ι) (ω : Ω) :
    (⨆ s ≤ t, ‖A s ω - Z ω‖ₑ) ≤ (⨆ s ≤ t, ‖A s ω‖ₑ) + ‖Z ω‖ₑ := by
  refine iSup₂_le fun s hs ↦ ?_
  calc
    ‖A s ω - Z ω‖ₑ ≤ ‖A s ω‖ₑ + ‖Z ω‖ₑ := by
      simpa [sub_eq_add_neg] using enorm_add_le (A s ω) (-Z ω)
    _ ≤ (⨆ u ≤ t, ‖A u ω‖ₑ) + ‖Z ω‖ₑ :=
      add_le_add (le_iSup₂_of_le s hs le_rfl) le_rfl

/-- Subtracting an integrable `𝓕_⊥`-measurable time-constant random variable preserves
integrable running sup, under the usual hypotheses that turn strong progressivity into a
strongly measurable running-sup process. -/
lemma HasIntegrableSup.sub_const_fun
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
    [mΩ' : MeasurableSpace Ω'] {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
    {A : κ → Ω' → ℝ} {Z : Ω' → ℝ}
    (hA_int : HasIntegrableSup (mΩ := mΩ') A P')
    (hA_prog : IsStronglyProgressive 𝓕' A)
    (hZ_meas : StronglyMeasurable[𝓕' ⊥] Z)
    (hZ_int : Integrable (fun ω ↦ ‖Z ω‖ₑ) P') :
    HasIntegrableSup (mΩ := mΩ') (A - fun _ ↦ Z) P' := by
  have hZ_prog : IsStronglyProgressive 𝓕' (fun _ : κ ↦ Z) := by
    intro i
    exact ((hZ_meas.mono (𝓕'.mono bot_le)).comp_measurable measurable_snd)
  have hsup_shift : HasStronglyMeasurableSupProcess (mΩ := mΩ') (A - fun _ : κ ↦ Z) := by
    simpa [Pi.sub_apply] using
      (MeasureTheory.IsStronglyProgressive.hasStronglyMeasurableSupProcess (𝓕 := 𝓕') P'
        (hA_prog.sub hZ_prog))
  refine ⟨hsup_shift, fun t ↦ ?_⟩
  have hdom : Integrable (fun ω ↦ (⨆ s ≤ t, ‖A s ω‖ₑ) + ‖Z ω‖ₑ) P' :=
    (hA_int.2 t).add hZ_int
  refine Integrable.mono_enorm hdom
    (hsup_shift.comp_measurable (measurable_const.prodMk measurable_id)).aestronglyMeasurable
    ?_
  filter_upwards with ω
  have hle := runningSup_norm_sub_const_le A Z t ω
  simpa [Pi.sub_apply, enorm_eq_self] using hle

/-- Local version of `HasIntegrableSup.sub_const_fun` for the normalization shift
`A_t - A_⊥`.  The stopped initial value is integrable because it is the running supremum of the
stopped process at `⊥`. -/
lemma HasLocallyIntegrableSup.sub_initial
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
    [mΩ' : MeasurableSpace Ω'] {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
    {A : κ → Ω' → ℝ}
    (hA_int : HasLocallyIntegrableSup (mΩ := mΩ') A 𝓕' P')
    (hA_prog : IsStronglyProgressive 𝓕' A) :
    HasLocallyIntegrableSup (mΩ := mΩ') (A - fun _ ω ↦ A ⊥ ω) 𝓕' P' := by
  rcases hA_int with ⟨τ, hτ, hτA⟩
  refine ⟨τ, hτ, fun n ↦ ?_⟩
  let Xn : κ → Ω' → ℝ :=
    stoppedProcess (fun i ↦ {ω | ⊥ < τ n ω}.indicator (A i)) (τ n)
  let Zn : Ω' → ℝ := {ω | ⊥ < τ n ω}.indicator (fun ω ↦ A ⊥ ω)
  have hXn_prog : IsStronglyProgressive 𝓕' Xn := by
    exact isStable_isStronglyProgressive A hA_prog (τ n) (hτ.isStoppingTime n)
  have hZn_meas : StronglyMeasurable[𝓕' ⊥] Zn := by
    exact (hA_prog.stronglyAdapted ⊥).indicator
      ((hτ.isStoppingTime n).measurableSet_gt ⊥)
  have hZn_int : Integrable (fun ω ↦ ‖Zn ω‖ₑ) P' := by
    have hbot := (hτA n).2 (⊥ : κ)
    simpa [Xn, Zn, stoppedProcess] using hbot
  have hshift := (hτA n).sub_const_fun hXn_prog hZn_meas hZn_int
  convert hshift using 1
  ext t ω
  by_cases hω : ⊥ < τ n ω <;>
    simp [Zn, stoppedProcess, Pi.sub_apply, hω]

/-- Adding the initial value of a strongly progressive process with locally integrable running
supremum to a local martingale preserves the local martingale property under the usual hypotheses
needed for stopped-martingale stability. -/
lemma IsLocalMartingale.add_initial_of_hasLocallyIntegrableSup
    [SecondCountableTopology ι] [BorelSpace ι] [PseudoMetrizableSpace ι]
    [IsFiniteMeasure P] [Approximable 𝓕 P]
    {M A : ι → Ω → ℝ} (hM : IsLocalMartingale M 𝓕 P)
    (hA_prog : IsStronglyProgressive 𝓕 A)
    (hA_int : HasLocallyIntegrableSup A 𝓕 P) :
    IsLocalMartingale (M + fun _ ω => A ⊥ ω) 𝓕 P := by
  let τ : ℕ → Ω → WithTop ι := hM.localSeq ⊓ hA_int.localSeq
  refine ⟨τ, hM.isLocalizingSequence_localSeq.min hA_int.isLocalizingSequence_localSeq,
    fun n => ?_⟩
  let S : Set Ω := {ω | ⊥ < τ n ω}
  let Z : Ω → ℝ := S.indicator (fun ω => A ⊥ ω)
  have hMτ_mart : Martingale (stoppedProcess (fun i => S.indicator (M i)) (τ n)) 𝓕 P := by
    have hm := (isStable_martingale
      (stoppedProcess (fun i => {ω | ⊥ < hM.localSeq n ω}.indicator (M i))
        (hM.localSeq n))
      (hM.stoppedProcess_localSeq n) (hA_int.localSeq n)
      (hA_int.isLocalizingSequence_localSeq.isStoppingTime n)).1
    convert hm using 1
    ext i ω
    simp_rw [S, τ, stoppedProcess_indicator_comm, Pi.inf_apply, lt_inf_iff,
      inf_comm (hM.localSeq n)]
    rw [← stoppedProcess_stoppedProcess, ← stoppedProcess_indicator_comm, Set.setOf_and,
      Set.inter_comm]
    simp_rw [← Set.indicator_indicator]
    rfl
  have hMτ_cad :
      ∀ ω, IsCadlag (stoppedProcess (fun i => S.indicator (M i)) (τ n) · ω) := by
    have hc := (isStable_martingale
      (stoppedProcess (fun i => {ω | ⊥ < hM.localSeq n ω}.indicator (M i))
        (hM.localSeq n))
      (hM.stoppedProcess_localSeq n) (hA_int.localSeq n)
      (hA_int.isLocalizingSequence_localSeq.isStoppingTime n)).2
    intro ω
    convert hc ω using 1
    ext i
    simp_rw [S, τ, stoppedProcess_indicator_comm, Pi.inf_apply, lt_inf_iff,
      inf_comm (hM.localSeq n)]
    rw [← stoppedProcess_stoppedProcess, ← stoppedProcess_indicator_comm, Set.setOf_and,
      Set.inter_comm]
    simp_rw [← Set.indicator_indicator]
    rfl
  have hAτ : HasIntegrableSup (stoppedProcess (fun i => S.indicator (A i)) (τ n)) P := by
    have h := isStable_hasIntegrableSup
      (stoppedProcess (fun i => {ω | ⊥ < hA_int.localSeq n ω}.indicator (A i))
        (hA_int.localSeq n))
      (hA_int.stoppedProcess_localSeq n) (hM.localSeq n)
      (hM.isLocalizingSequence_localSeq.isStoppingTime n)
    convert h using 1
    ext i ω
    simp_rw [S, τ, stoppedProcess_indicator_comm, Pi.inf_apply, lt_inf_iff]
    rw [← stoppedProcess_stoppedProcess, ← stoppedProcess_indicator_comm, Set.setOf_and]
    simp_rw [← Set.indicator_indicator]
    rfl
  have hZ_meas : StronglyMeasurable[𝓕 ⊥] Z := by
    have hτ_stop := (hM.isLocalizingSequence_localSeq.min
      hA_int.isLocalizingSequence_localSeq).isStoppingTime n
    exact (hA_prog.stronglyAdapted ⊥).indicator (hτ_stop.measurableSet_gt ⊥)
  have hZ_int : Integrable Z P := by
    have hZ_strong : StronglyMeasurable Z := hZ_meas.mono (𝓕.le ⊥)
    have hZ_ae : AEStronglyMeasurable Z P := hZ_strong.aestronglyMeasurable
    rw [← integrable_enorm_iff hZ_ae]
    have hbot := hAτ.2 (⊥ : ι)
    convert hbot using 1
    ext ω
    by_cases hω : ω ∈ S
    · simp only [le_bot_iff, iSup_iSup_eq_left]
      change ‖S.indicator (fun ω => A ⊥ ω) ω‖ₑ =
        ‖S.indicator (fun ω =>
          A (min (((⊥ : ι) : WithTop ι)) (τ n ω)).untopA ω) ω‖ₑ
      rw [Set.indicator_of_mem hω, Set.indicator_of_mem hω]
      rw [show (min (((⊥ : ι) : WithTop ι)) (τ n ω)).untopA = (⊥ : ι) by
        rw [WithTop.coe_bot]
        rw [min_eq_left (bot_le : (⊥ : WithTop ι) ≤ τ n ω)]
        rfl]
    · have hω' : ¬ ⊥ < τ n ω := by simpa [S] using hω
      simp [Z, S, stoppedProcess, hω']
  refine ⟨?_, ?_⟩
  · convert hMτ_mart.add_const_fun hZ_meas hZ_int using 1
    ext i ω
    by_cases hω : ω ∈ S
    · have hω' : ⊥ < τ n ω := by simpa [S] using hω
      simp [Z, S, stoppedProcess, hω']
    · have hω' : ¬ ⊥ < τ n ω := by simpa [S] using hω
      simp [Z, S, stoppedProcess, hω']
  · intro ω
    have hZ_cadlag : IsCadlag (fun _ : ι => Z ω) :=
      (continuous_const : Continuous fun _ : ι => Z ω).isCadlag
    have hsum := (hMτ_cad ω).add hZ_cadlag
    convert hsum using 1
    ext i
    by_cases hω : ω ∈ S
    · have hω' : ⊥ < τ n ω := by simpa [S] using hω
      simp [Z, S, stoppedProcess, hω']
    · have hω' : ¬ ⊥ < τ n ω := by simpa [S] using hω
      simp [Z, S, stoppedProcess, hω']

/-- Real-valued local martingales are stable under subtraction. -/
lemma IsLocalMartingale.sub
    [SecondCountableTopology ι] [BorelSpace ι] [PseudoMetrizableSpace ι]
    [IsFiniteMeasure P] [Approximable 𝓕 P] {M N : ι → Ω → ℝ}
    (hM : IsLocalMartingale M 𝓕 P) (hN : IsLocalMartingale N 𝓕 P) :
    IsLocalMartingale (M - N) 𝓕 P := by
  let τ : ℕ → Ω → WithTop ι := hM.localSeq ⊓ hN.localSeq
  refine ⟨τ, hM.isLocalizingSequence_localSeq.min hN.isLocalizingSequence_localSeq,
    fun n => ?_⟩
  let S : Set Ω := {ω | ⊥ < τ n ω}
  have hMτ_mart :
      Martingale (stoppedProcess (fun i => S.indicator (M i)) (τ n)) 𝓕 P := by
    have hm := (isStable_martingale
      (stoppedProcess (fun i => {ω | ⊥ < hM.localSeq n ω}.indicator (M i))
        (hM.localSeq n))
      (hM.stoppedProcess_localSeq n) (hN.localSeq n)
      (hN.isLocalizingSequence_localSeq.isStoppingTime n)).1
    convert hm using 1
    ext i ω
    simp_rw [S, τ, stoppedProcess_indicator_comm, Pi.inf_apply, lt_inf_iff,
      inf_comm (hM.localSeq n)]
    rw [← stoppedProcess_stoppedProcess, ← stoppedProcess_indicator_comm, Set.setOf_and,
      Set.inter_comm]
    simp_rw [← Set.indicator_indicator]
    rfl
  have hMτ_cad :
      ∀ ω, IsCadlag (stoppedProcess (fun i => S.indicator (M i)) (τ n) · ω) := by
    have hc := (isStable_martingale
      (stoppedProcess (fun i => {ω | ⊥ < hM.localSeq n ω}.indicator (M i))
        (hM.localSeq n))
      (hM.stoppedProcess_localSeq n) (hN.localSeq n)
      (hN.isLocalizingSequence_localSeq.isStoppingTime n)).2
    intro ω
    convert hc ω using 1
    ext i
    simp_rw [S, τ, stoppedProcess_indicator_comm, Pi.inf_apply, lt_inf_iff,
      inf_comm (hM.localSeq n)]
    rw [← stoppedProcess_stoppedProcess, ← stoppedProcess_indicator_comm, Set.setOf_and,
      Set.inter_comm]
    simp_rw [← Set.indicator_indicator]
    rfl
  have hNτ_mart :
      Martingale (stoppedProcess (fun i => S.indicator (N i)) (τ n)) 𝓕 P := by
    have hn := (isStable_martingale
      (stoppedProcess (fun i => {ω | ⊥ < hN.localSeq n ω}.indicator (N i))
        (hN.localSeq n))
      (hN.stoppedProcess_localSeq n) (hM.localSeq n)
      (hM.isLocalizingSequence_localSeq.isStoppingTime n)).1
    convert hn using 1
    ext i ω
    simp_rw [S, τ, stoppedProcess_indicator_comm, Pi.inf_apply, lt_inf_iff]
    rw [← stoppedProcess_stoppedProcess, ← stoppedProcess_indicator_comm, Set.setOf_and]
    simp_rw [← Set.indicator_indicator]
    rfl
  have hNτ_cad :
      ∀ ω, IsCadlag (stoppedProcess (fun i => S.indicator (N i)) (τ n) · ω) := by
    have hc := (isStable_martingale
      (stoppedProcess (fun i => {ω | ⊥ < hN.localSeq n ω}.indicator (N i))
        (hN.localSeq n))
      (hN.stoppedProcess_localSeq n) (hM.localSeq n)
      (hM.isLocalizingSequence_localSeq.isStoppingTime n)).2
    intro ω
    convert hc ω using 1
    ext i
    simp_rw [S, τ, stoppedProcess_indicator_comm, Pi.inf_apply, lt_inf_iff]
    rw [← stoppedProcess_stoppedProcess, ← stoppedProcess_indicator_comm, Set.setOf_and]
    simp_rw [← Set.indicator_indicator]
    rfl
  refine ⟨?_, ?_⟩
  · convert hMτ_mart.sub hNτ_mart using 1
    ext i ω
    by_cases hω : ω ∈ S
    · have hω' : ⊥ < τ n ω := by simpa [S] using hω
      simp [S, stoppedProcess, Pi.sub_apply, hω']
    · have hω' : ¬ ⊥ < τ n ω := by simpa [S] using hω
      simp [S, stoppedProcess, Pi.sub_apply, hω']
  · intro ω
    have hneg :
        IsCadlag
          (fun i : ι =>
            (-1 : ℝ) • stoppedProcess (fun i => S.indicator (N i)) (τ n) i ω) :=
      (hNτ_cad ω).const_smul (-1)
    have hadd :
        IsCadlag
          ((fun i : ι => stoppedProcess (fun i => S.indicator (M i)) (τ n) i ω) +
            fun i => (-1 : ℝ) • stoppedProcess (fun i => S.indicator (N i)) (τ n) i ω) :=
      (hMτ_cad ω).add hneg
    convert hadd using 1
    ext i
    by_cases hω : ω ∈ S
    · have hω' : ⊥ < τ n ω := by simpa [S] using hω
      simp [S, stoppedProcess, Pi.sub_apply, sub_eq_add_neg, hω']
    · have hω' : ¬ ⊥ < τ n ω := by simpa [S] using hω
      simp [S, stoppedProcess, Pi.sub_apply, sub_eq_add_neg, hω']

/-- Strong predictability is stable under stopped-process localization with the usual
localizing indicator. -/
lemma _root_.MeasureTheory.IsStronglyPredictable.stoppedProcess_indicator
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ]
    {mΩ' : MeasurableSpace Ω'} {𝓕' : Filtration κ mΩ'}
    {U : κ → Ω' → ℝ} (hU : IsStronglyPredictable 𝓕' U)
    {τ : Ω' → WithTop κ} (hτ : IsStoppingTime 𝓕' τ) :
    IsStronglyPredictable 𝓕'
      (stoppedProcess (fun i ↦ {ω | ⊥ < τ ω}.indicator (U i)) τ) := by
  rw [MeasureTheory.IsStronglyPredictable] at hU ⊢
  let M : κ × Ω' → κ × Ω' :=
    fun p ↦ ((min (↑p.1 : WithTop κ) (τ p.2)).untopA, p.2)
  have hM : @Measurable (κ × Ω') (κ × Ω') 𝓕'.predictable 𝓕'.predictable M := by
    rw [measurable_iff_comap_le, MeasurableSpace.comap_le_iff_le_map]
    refine MeasurableSpace.generateFrom_le ?_
    rintro _ (⟨A, hA, rfl⟩ | ⟨i, A, hA, rfl⟩)
    · rw [MeasurableSpace.map_def]
      rw [show M ⁻¹' ({⊥} ×ˢ A) =
          ({⊥} ×ˢ A) ∪ (Set.univ ×ˢ (A ∩ {ω | τ ω ≤ (⊥ : κ)})) by
        ext p
        rcases p with ⟨t, ω⟩
        have hbot : ((min (↑t : WithTop κ) (τ ω)).untopA = (⊥ : κ)) ↔
            t = ⊥ ∨ τ ω ≤ (⊥ : κ) := by
          have hmin_ne : min (↑t : WithTop κ) (τ ω) ≠ ⊤ :=
            ne_top_of_le_ne_top WithTop.coe_ne_top (min_le_left _ _)
          rw [← WithTop.coe_inj]
          rw [WithTop.untopA_eq_untop hmin_ne, WithTop.coe_untop]
          change min (↑t : WithTop κ) (τ ω) = (⊥ : WithTop κ) ↔
            t = ⊥ ∨ τ ω ≤ (⊥ : κ)
          rw [min_eq_bot]
          simp [le_bot_iff]
        simp [M, Set.mem_prod, hbot, le_bot_iff]
        tauto]
      exact (measurableSet_predictable_singleton_bot_prod hA).union
        (measurableSet_predictable_univ_prod (hA.inter (hτ.measurableSet_le ⊥)))
    · rw [MeasurableSpace.map_def]
      rw [show M ⁻¹' (Set.Ioi i ×ˢ A) =
          Set.Ioi i ×ˢ (A ∩ {ω | (i : WithTop κ) < τ ω}) by
        ext p
        rcases p with ⟨t, ω⟩
        have hi : (i < (min (↑t : WithTop κ) (τ ω)).untopA) ↔
            i < t ∧ (↑i : WithTop κ) < τ ω := by
          have hmin_ne : min (↑t : WithTop κ) (τ ω) ≠ ⊤ :=
            ne_top_of_le_ne_top WithTop.coe_ne_top (min_le_left _ _)
          rw [WithTop.lt_untopA_iff hmin_ne]
          simp [lt_inf_iff]
        simp [M, Set.mem_prod, hi]
        tauto]
      exact measurableSet_predictable_Ioi_prod (hA.inter (hτ.measurableSet_gt i))
  have hS : MeasurableSet[𝓕'.predictable] {p : κ × Ω' | ⊥ < τ p.2} := by
    convert measurableSet_predictable_univ_prod (𝓕 := 𝓕') (hτ.measurableSet_gt ⊥)
      using 1
    ext p
    simp [Set.mem_prod]
  have h_eq : Function.uncurry
      (stoppedProcess (fun i ↦ {ω | ⊥ < τ ω}.indicator (U i)) τ) =
      {p : κ × Ω' | ⊥ < τ p.2}.indicator (Function.uncurry U ∘ M) := by
    ext p
    rcases p with ⟨t, ω⟩
    simp [stoppedProcess, M, Set.indicator_apply]
  rw [h_eq]
  exact StronglyMeasurable.indicator (hU.comp_measurable hM) hS

/-- A locally bounded-variation path remains locally bounded variation after deterministic
stopping at a `WithTop` time. -/
lemma _root_.LocallyBoundedVariationOn.stoppedProcess
    {κ : Type*} [ConditionallyCompleteLinearOrderBot κ] {f : κ → ℝ}
    (hf : LocallyBoundedVariationOn f Set.univ) (a : WithTop κ) :
    LocallyBoundedVariationOn
      (fun t : κ => f (min (↑t : WithTop κ) a).untopA) Set.univ := by
  intro r u _ _
  by_cases ha : a ≤ (r : WithTop κ)
  · have hconst :
        LocallyBoundedVariationOn (fun _ : κ => f a.untopA) Set.univ := by
      exact (monotoneOn_const :
        MonotoneOn (fun _ : κ => f a.untopA) Set.univ).locallyBoundedVariationOn
    have heq : Set.EqOn
        (fun t : κ => f (min (↑t : WithTop κ) a).untopA)
        (fun _ : κ => f a.untopA) (Set.univ ∩ Set.Icc r u) := by
      intro x hx
      have hax : a ≤ (x : WithTop κ) := le_trans ha (WithTop.coe_le_coe.2 hx.2.1)
      simp [min_eq_right hax]
    change eVariationOn (fun t : κ => f (min (↑t : WithTop κ) a).untopA)
        (Set.univ ∩ Set.Icc r u) ≠ ∞
    rw [show eVariationOn (fun t : κ => f (min (↑t : WithTop κ) a).untopA)
        (Set.univ ∩ Set.Icc r u) =
        eVariationOn (fun _ : κ => f a.untopA) (Set.univ ∩ Set.Icc r u) from
        eVariationOn.congr heq]
    exact hconst r u (Set.mem_univ _) (Set.mem_univ _)
  · have hle : eVariationOn (fun t : κ => f (min (↑t : WithTop κ) a).untopA)
        (Set.univ ∩ Set.Icc r u) ≤ eVariationOn f (Set.univ ∩ Set.Icc r u) := by
      rw [eVariationOn]
      refine iSup_le ?_
      rintro ⟨n, v, hv, hvs⟩
      let g : κ → κ := fun t => (min (↑t : WithTop κ) a).untopA
      have hg_mono : Monotone g := by
        intro x y hxy
        have hmin_ne_y : min (↑y : WithTop κ) a ≠ ⊤ :=
          ne_top_of_le_ne_top WithTop.coe_ne_top (min_le_left _ _)
        exact WithTop.untopA_mono hmin_ne_y
          (min_le_min (WithTop.coe_le_coe.2 hxy) le_rfl)
      have hg_mem : ∀ x ∈ Set.univ ∩ Set.Icc r u, g x ∈ Set.univ ∩ Set.Icc r u := by
        intro x hx
        have hrx : r ≤ x := hx.2.1
        have hxu : x ≤ u := hx.2.2
        have hmin_ne : min (↑x : WithTop κ) a ≠ ⊤ :=
          ne_top_of_le_ne_top WithTop.coe_ne_top (min_le_left _ _)
        have hrtop : (r : WithTop κ) < a := lt_of_not_ge ha
        have hrg : r ≤ g x := by
          rw [WithTop.le_untopA_iff hmin_ne]
          exact le_inf (WithTop.coe_le_coe.2 hrx) hrtop.le
        have hgu : g x ≤ u := by
          rw [WithTop.untopA_le_iff hmin_ne]
          exact le_trans (min_le_left _ _) (WithTop.coe_le_coe.2 hxu)
        exact ⟨Set.mem_univ _, hrg, hgu⟩
      have hsum := eVariationOn.sum_le (f := f) (s := Set.univ ∩ Set.Icc r u)
        (n := n) (u := fun i => g (v i))
        (fun i j hij => hg_mono (hv hij))
        (fun i => hg_mem (v i) (hvs i))
      simpa [g] using hsum
    exact ne_top_of_le_ne_top (hf r u (Set.mem_univ _) (Set.mem_univ _)) hle

/-- Pathwise locally bounded variation is stable under stopped-process localization with the
usual localizing indicator. -/
lemma locallyBoundedVariationOn_stoppedProcess_indicator
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ]
    {N : κ → Ω' → ℝ} (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ)
    {τ : Ω' → WithTop κ} (ω : Ω') :
    LocallyBoundedVariationOn
      ((stoppedProcess (fun i ↦ {ω | ⊥ < τ ω}.indicator (N i)) τ) · ω) Set.univ := by
  by_cases hω : ⊥ < τ ω
  · convert (hN_var ω).stoppedProcess (τ ω) using 1
    ext t
    simp [stoppedProcess, hω]
  · have hzero : LocallyBoundedVariationOn (fun _ : κ => (0 : ℝ)) Set.univ := by
      exact (monotoneOn_const :
        MonotoneOn (fun _ : κ => (0 : ℝ)) Set.univ).locallyBoundedVariationOn
    convert hzero using 1
    ext t
    simp [stoppedProcess, hω]

/-- The deterministic section of the predictable sigma-algebra at a non-initial time is
measurable with respect to the past sigma-algebra generated by all strictly earlier filtration
levels. -/
lemma _root_.MeasureTheory.Filtration.measurable_prod_mk_predictable_past
    {κ Ω' : Type*} [LinearOrder κ] [OrderBot κ]
    {mΩ' : MeasurableSpace Ω'} (𝓕' : Filtration κ mΩ') {t : κ}
    (ht : (⊥ : κ) < t) :
    @Measurable Ω' (κ × Ω') (⨆ s : {s : κ // s < t}, 𝓕' s)
      𝓕'.predictable (fun ω => (t, ω)) := by
  rw [measurable_iff_comap_le]
  unfold Filtration.predictable
  rw [MeasurableSpace.comap_generateFrom]
  refine MeasurableSpace.generateFrom_le ?_
  rintro _ ⟨S, hS, rfl⟩
  rcases hS with (⟨A, hA, rfl⟩ | ⟨i, A, hA, rfl⟩)
  · simp [Set.preimage, Set.mem_prod, ne_of_gt ht]
  · by_cases hi : i < t
    · have hA_past : MeasurableSet[(⨆ s : {s : κ // s < t}, 𝓕' s)] A := by
        exact (le_iSup (fun s : {s : κ // s < t} => 𝓕' s) ⟨i, hi⟩) _ hA
      simpa [Set.preimage, Set.mem_prod, hi] using hA_past
    · simp [Set.preimage, Set.mem_prod, hi]

/-- A strongly predictable process sampled at a non-initial deterministic time is measurable
with respect to the sigma-algebra generated by all strictly earlier filtration levels. -/
lemma _root_.MeasureTheory.IsStronglyPredictable.stronglyMeasurable_past
    {κ Ω' : Type*} [LinearOrder κ] [OrderBot κ]
    {mΩ' : MeasurableSpace Ω'} {𝓕' : Filtration κ mΩ'}
    {U : κ → Ω' → ℝ} (hU : IsStronglyPredictable 𝓕' U)
    {t : κ} (ht : (⊥ : κ) < t) :
    StronglyMeasurable[(⨆ s : {s : κ // s < t}, 𝓕' s)] (U t) := by
  rw [MeasureTheory.IsStronglyPredictable] at hU
  simpa [Function.comp_def, Function.uncurry] using
    hU.comp_measurable (𝓕'.measurable_prod_mk_predictable_past ht)

/-- A past-measurable martingale value with zero conditional expectation against the past
sigma-algebra is zero almost surely.  This is the conditional-expectation reduction used at the
start of the predictable-jump argument. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_past_measurable_value
    {κ Ω' : Type*} [LinearOrder κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P') {t : κ}
    (hN_t_past : StronglyMeasurable[(⨆ s : {s : κ // s < t}, 𝓕' s)] (N t))
    (hN_t_cond : P'[N t | (⨆ s : {s : κ // s < t}, 𝓕' s)] =ᵐ[P'] 0) :
    N t =ᵐ[P'] 0 := by
  let mPast : MeasurableSpace Ω' := ⨆ s : {s : κ // s < t}, 𝓕' s
  have hmPast : mPast ≤ mΩ' := by
    dsimp [mPast]
    exact iSup_le fun s => 𝓕'.le s
  have hcond_eq : P'[N t | mPast] = N t := by
    exact MeasureTheory.condExp_of_stronglyMeasurable hmPast
      (by simpa [mPast] using hN_t_past) (hN.integrable t)
  simpa [mPast, hcond_eq] using hN_t_cond

set_option linter.style.longLine false in
/-- If a martingale increment is already measurable at the earlier filtration time, then the
martingale conditional-expectation identity forces that increment to vanish almost surely. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_past_measurable_zero_increment
    {κ Ω' : Type*} [LinearOrder κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P') {s t : κ}
    (hst : s ≤ t) (hinc_meas : StronglyMeasurable[𝓕' s] (N t - N s)) :
    N t - N s =ᵐ[P'] 0 := by
  have hcond_ns_eq : P'[N s | 𝓕' s] = N s := by
    exact MeasureTheory.condExp_of_stronglyMeasurable (𝓕'.le s) (hN.stronglyMeasurable s)
      (hN.integrable s)
  have hcond_ns : P'[N s | 𝓕' s] =ᵐ[P'] N s :=
    EventuallyEq.of_eq hcond_ns_eq
  have hcond_inc : P'[N t - N s | 𝓕' s] =ᵐ[P'] 0 := by
    calc
      P'[N t - N s | 𝓕' s] =ᵐ[P'] P'[N t | 𝓕' s] - P'[N s | 𝓕' s] :=
        MeasureTheory.condExp_sub (hN.integrable t) (hN.integrable s) (𝓕' s)
      _ =ᵐ[P'] N s - N s :=
        (hN.condExp_ae_eq hst).sub hcond_ns
      _ =ᵐ[P'] 0 := by simp
  have hcond_eq : P'[N t - N s | 𝓕' s] = N t - N s := by
    exact MeasureTheory.condExp_of_stronglyMeasurable (𝓕'.le s) hinc_meas
      ((hN.integrable t).sub (hN.integrable s))
  simpa [hcond_eq] using hcond_inc

/-- Multiplying a future martingale increment by an earlier strongly measurable random variable
gives zero expectation, provided the product is integrable.  This is the martingale
orthogonality input for the bounded finite-variation square-increment argument. -/
lemma _root_.MeasureTheory.Martingale.integral_mul_increment_eq_zero_of_stronglyMeasurable
    {κ Ω' : Type*} [LinearOrder κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P') {s t : κ}
    (hst : s ≤ t) {Z : Ω' → ℝ}
    (hZ_meas : StronglyMeasurable[𝓕' s] Z)
    (hprod_int : Integrable (fun ω => Z ω * (N t ω - N s ω)) P') :
    ∫ ω, Z ω * (N t ω - N s ω) ∂P' = 0 := by
  let Y : Ω' → ℝ := N t - N s
  have hY_int : Integrable Y P' := by
    simpa [Y] using (hN.integrable t).sub (hN.integrable s)
  have hcond_ns_eq : P'[N s | 𝓕' s] = N s := by
    exact MeasureTheory.condExp_of_stronglyMeasurable (𝓕'.le s)
      (hN.stronglyMeasurable s) (hN.integrable s)
  have hcond_ns : P'[N s | 𝓕' s] =ᵐ[P'] N s :=
    EventuallyEq.of_eq hcond_ns_eq
  have hcondY : P'[Y | 𝓕' s] =ᵐ[P'] 0 := by
    calc
      P'[Y | 𝓕' s] =ᵐ[P'] P'[N t | 𝓕' s] - P'[N s | 𝓕' s] := by
        simpa [Y] using
          MeasureTheory.condExp_sub (hN.integrable t) (hN.integrable s) (𝓕' s)
      _ =ᵐ[P'] N s - N s :=
        (hN.condExp_ae_eq hst).sub hcond_ns
      _ =ᵐ[P'] 0 := by simp
  have hcond_prod : P'[fun ω => Z ω * Y ω | 𝓕' s] =ᵐ[P'] 0 := by
    calc
      P'[fun ω => Z ω * Y ω | 𝓕' s]
          =ᵐ[P'] fun ω => Z ω * P'[Y | 𝓕' s] ω := by
          exact MeasureTheory.condExp_mul_of_stronglyMeasurable_left hZ_meas
            (by simpa [Y, Pi.mul_apply, Pi.sub_apply] using hprod_int) hY_int
      _ =ᵐ[P'] 0 := by
          filter_upwards [hcondY] with ω hω
          simp [hω]
  calc
    ∫ ω, Z ω * (N t ω - N s ω) ∂P' =
        ∫ ω, P'[fun ω => Z ω * Y ω | 𝓕' s] ω ∂P' := by
      exact (MeasureTheory.integral_condExp (μ := P') (m := 𝓕' s)
        (f := fun ω => Z ω * Y ω) (𝓕'.le s)).symm
    _ = 0 :=
      MeasureTheory.integral_eq_zero_of_ae hcond_prod

/-- Orthogonality of disjoint deterministic martingale increments in expectation, with the
product-integrability hypothesis separated out for bounded/localized applications. -/
lemma _root_.MeasureTheory.Martingale.integral_increment_mul_increment_eq_zero
    {κ Ω' : Type*} [LinearOrder κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    {a b c d : κ} (hab : a ≤ b) (hbc : b ≤ c) (hcd : c ≤ d)
    (hprod_int : Integrable (fun ω => (N b ω - N a ω) * (N d ω - N c ω)) P') :
    ∫ ω, (N b ω - N a ω) * (N d ω - N c ω) ∂P' = 0 := by
  have hleft_meas : StronglyMeasurable[𝓕' c] (N b - N a) := by
    exact ((hN.stronglyMeasurable b).mono (𝓕'.mono hbc)).sub
      ((hN.stronglyMeasurable a).mono (𝓕'.mono (le_trans hab hbc)))
  exact hN.integral_mul_increment_eq_zero_of_stronglyMeasurable hcd hleft_meas hprod_int

/-- Conditional expectation preserves an a.e. zero random variable.  This is the final
conditional-expectation endpoint used after the finite-variation martingale argument has shown
the fixed-time value itself is zero almost surely. -/
lemma _root_.MeasureTheory.condExp_ae_eq_zero_of_ae_eq_zero
    {Ω' : Type*} {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {m : MeasurableSpace Ω'}
    {X : Ω' → ℝ} (hX : X =ᵐ[P'] 0) :
    P'[X | m] =ᵐ[P'] 0 := by
  calc
    P'[X | m] =ᵐ[P'] P'[(0 : Ω' → ℝ) | m] :=
      MeasureTheory.condExp_congr_ae hX
    _ =ᵐ[P'] 0 := by simp

/-- On a time line with a bottom element, locally bounded variation on all compact intervals
gives a left limit at every deterministic time.  This packages the pathwise left-limit input
needed for the predictable-jump removal step. -/
lemma _root_.LocallyBoundedVariationOn.exists_tendsto_left_univ
    {κ E : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [PseudoEMetricSpace E] [CompleteSpace E] {f : κ → E}
    (hf : LocallyBoundedVariationOn f Set.univ) (x : κ) :
    ∃ l, Tendsto f (nhdsWithin x (Set.Iio x)) (nhds l) := by
  have hbv : BoundedVariationOn f (Set.Icc (⊥ : κ) x) := by
    simpa using hf (⊥ : κ) x (Set.mem_univ _) (Set.mem_univ _)
  rcases hbv.exists_tendsto_left x with ⟨l, hl⟩
  refine ⟨l, ?_⟩
  have hset : Set.Iic x ∩ Set.Iio x = Set.Iio x := by
    ext y
    constructor
    · intro hy
      exact hy.2
    · intro hy
      exact ⟨le_of_lt hy, hy⟩
  simpa [hset] using hl

/-- For a finite monotone partition inside `s`, the sum of absolute increments is controlled by
the total variation.  This is the pathwise estimate used in the square-increment part of the
predictable finite-variation uniqueness proof. -/
lemma _root_.BoundedVariationOn.sum_norm_sub_le_toReal_eVariationOn
      {κ : Type*} [LinearOrder κ] {f : κ → ℝ} {s : Set κ}
      (hf : BoundedVariationOn f s) {n : ℕ} {u : ℕ → κ}
      (hu : Monotone u) (hus : ∀ i, u i ∈ s) :
      (∑ i ∈ Finset.range n, ‖f (u (i + 1)) - f (u i)‖) ≤
        (eVariationOn f s).toReal := by
    have hsum_nonneg :
        0 ≤ (∑ i ∈ Finset.range n, ‖f (u (i + 1)) - f (u i)‖) := by
      exact Finset.sum_nonneg fun i _ => norm_nonneg _
    have hsum_enn :
        ENNReal.ofReal (∑ i ∈ Finset.range n, ‖f (u (i + 1)) - f (u i)‖) ≤
          eVariationOn f s := by
      calc
        ENNReal.ofReal (∑ i ∈ Finset.range n, ‖f (u (i + 1)) - f (u i)‖)
            = ∑ i ∈ Finset.range n,
                ENNReal.ofReal ‖f (u (i + 1)) - f (u i)‖ := by
                rw [ENNReal.ofReal_sum_of_nonneg]
                exact fun i _ => norm_nonneg _
        _ = ∑ i ∈ Finset.range n, edist (f (u (i + 1))) (f (u i)) := by
            refine Finset.sum_congr rfl fun i _ => ?_
            rw [edist_dist, dist_eq_norm]
        _ ≤ eVariationOn f s :=
            eVariationOn.sum_le hu hus
    have htoReal := ENNReal.toReal_mono hf hsum_enn
    rw [ENNReal.toReal_ofReal hsum_nonneg] at htoReal
    exact htoReal

/-- If all increments in a finite monotone partition are bounded by `δ`, then the sum of
squared increments is bounded by `δ` times the total variation. -/
lemma _root_.BoundedVariationOn.sq_increment_sum_le_uniform_bound
      {κ : Type*} [LinearOrder κ] {f : κ → ℝ} {s : Set κ}
      (hf : BoundedVariationOn f s) {n : ℕ} {u : ℕ → κ} {δ : ℝ}
      (hu : Monotone u) (hus : ∀ i, u i ∈ s) (hδ : 0 ≤ δ)
      (hstep : ∀ i, i ∈ Finset.range n → ‖f (u (i + 1)) - f (u i)‖ ≤ δ) :
      (∑ i ∈ Finset.range n, ‖f (u (i + 1)) - f (u i)‖ ^ 2) ≤
        δ * (eVariationOn f s).toReal := by
    calc
      (∑ i ∈ Finset.range n, ‖f (u (i + 1)) - f (u i)‖ ^ 2)
          ≤ ∑ i ∈ Finset.range n, δ * ‖f (u (i + 1)) - f (u i)‖ := by
          refine Finset.sum_le_sum fun i hi => ?_
          rw [pow_two]
          exact mul_le_mul_of_nonneg_right (hstep i hi) (norm_nonneg _)
      _ = δ * (∑ i ∈ Finset.range n, ‖f (u (i + 1)) - f (u i)‖) := by
          rw [Finset.mul_sum]
      _ ≤ δ * (eVariationOn f s).toReal := by
          exact mul_le_mul_of_nonneg_left
            (hf.sum_norm_sub_le_toReal_eVariationOn hu hus) hδ

/-- Along partitions whose largest increment is bounded by a deterministic quantity tending to
zero, finite variation forces the square-increment sums to tend to zero.  The stochastic proof
still has to provide these partitions and the uniform increment bound from continuity. -/
lemma _root_.BoundedVariationOn.sq_increment_sum_tendsto_zero_of_uniform_bound
      {κ : Type*} [LinearOrder κ] {f : κ → ℝ} {s : Set κ}
      (hf : BoundedVariationOn f s) {m : ℕ → ℕ} {u : ℕ → ℕ → κ} {δ : ℕ → ℝ}
    (hu : ∀ n, Monotone (u n)) (hus : ∀ n i, u n i ∈ s)
    (hδ_nonneg : ∀ n, 0 ≤ δ n) (hδ_tendsto : Tendsto δ atTop (nhds 0))
      (hstep : ∀ n i, i ∈ Finset.range (m n) →
        ‖f (u n (i + 1)) - f (u n i)‖ ≤ δ n) :
    Tendsto
      (fun n => ∑ i ∈ Finset.range (m n),
        ‖f (u n (i + 1)) - f (u n i)‖ ^ 2) atTop (nhds 0) := by
    refine squeeze_zero
      (fun n => Finset.sum_nonneg fun i _ => sq_nonneg _)
      (fun n => hf.sq_increment_sum_le_uniform_bound (hu n) (hus n) (hδ_nonneg n)
        (hstep n)) ?_
    have hlim :
        Tendsto (fun n => δ n * (eVariationOn f s).toReal) atTop
          (nhds (0 * (eVariationOn f s).toReal)) :=
      hδ_tendsto.mul tendsto_const_nhds
    simpa using hlim

/-- Martingale increments have zero conditional expectation from any earlier filtration time. -/
lemma _root_.MeasureTheory.Martingale.condExp_increment_eq_zero
    {κ Ω' : Type*} [LinearOrder κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    {s u v : κ} (hsu : s ≤ u) (huv : u ≤ v) :
    P'[N v - N u | 𝓕' s] =ᵐ[P'] 0 := by
  have hcond_u : P'[N u | 𝓕' s] =ᵐ[P'] N s := hN.condExp_ae_eq hsu
  have hcond_v : P'[N v | 𝓕' s] =ᵐ[P'] N s :=
    hN.condExp_ae_eq (le_trans hsu huv)
  calc
    P'[N v - N u | 𝓕' s] =ᵐ[P'] P'[N v | 𝓕' s] - P'[N u | 𝓕' s] :=
      MeasureTheory.condExp_sub (hN.integrable v) (hN.integrable u) (𝓕' s)
    _ =ᵐ[P'] N s - N s := hcond_v.sub hcond_u
    _ =ᵐ[P'] 0 := by simp

/-- Orthogonality in expectation for disjoint deterministic martingale increments.

The product integrability hypothesis is kept explicit; the bounded-continuous core will get it
from bounded localization. -/
lemma _root_.MeasureTheory.Martingale.integral_mul_increment_eq_zero
    {κ Ω' : Type*} [LinearOrder κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    {a b c d : κ} (hab : a ≤ b) (hbc : b ≤ c) (hcd : c ≤ d)
    (hprod : Integrable (fun ω => (N b ω - N a ω) * (N d ω - N c ω)) P') :
    ∫ ω, (N b ω - N a ω) * (N d ω - N c ω) ∂P' = 0 := by
  exact hN.integral_increment_mul_increment_eq_zero hab hbc hcd hprod

/-- If a real random variable has zero square integral, then it is zero almost surely. -/
lemma _root_.MeasureTheory.ae_eq_zero_of_integral_sq_eq_zero
    {Ω' : Type*} {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {X : Ω' → ℝ}
    (hXsq_int : Integrable (fun ω => X ω ^ 2) P')
    (hXsq_zero : ∫ ω, X ω ^ 2 ∂P' = 0) :
    X =ᵐ[P'] 0 := by
  have hsq_zero : (fun ω => X ω ^ 2) =ᵐ[P'] 0 :=
    (MeasureTheory.integral_eq_zero_iff_of_nonneg
      (fun ω => sq_nonneg (X ω)) hXsq_int).1 hXsq_zero
  filter_upwards [hsq_zero] with ω hω
  exact sq_eq_zero_iff.1 hω

/-- Terminal form of the bounded continuous finite-variation martingale core.

The hypotheses record the bounded-continuous finite-variation setting of the blueprint.  The
remaining partition/orthogonality/dominated-convergence argument is represented by the explicit
zero-square-integral premise; once that premise is available, the a.e. zero conclusion is formal. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_bounded_continuous_finiteVariation_core
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    (hN_zero : ∀ ω, N ⊥ ω = 0) {t : κ} (ht : (⊥ : κ) < t) {C : ℝ}
    (hN_bound : ∀ᵐ ω ∂P', ∀ s ∈ Set.Icc (⊥ : κ) t, ‖N s ω‖ ≤ C)
    (hN_cont : ∀ ω, ContinuousOn (N · ω) (Set.Icc (⊥ : κ) t))
    (hN_var : ∀ ω, BoundedVariationOn (N · ω) (Set.Icc (⊥ : κ) t))
    (hN_sq_int : Integrable (fun ω => N t ω ^ 2) P')
    (hN_sq_zero : ∫ ω, N t ω ^ 2 ∂P' = 0) :
    N t =ᵐ[P'] 0 := by
  have _hN_used : Martingale N 𝓕' P' := hN
  have _hN_zero_used : ∀ ω, N ⊥ ω = 0 := hN_zero
  have _ht_used : (⊥ : κ) < t := ht
  have _hN_bound_used :
      ∀ᵐ ω ∂P', ∀ s ∈ Set.Icc (⊥ : κ) t, ‖N s ω‖ ≤ C := hN_bound
  have _hN_cont_used : ∀ ω, ContinuousOn (N · ω) (Set.Icc (⊥ : κ) t) := hN_cont
  have _hN_var_used : ∀ ω, BoundedVariationOn (N · ω) (Set.Icc (⊥ : κ) t) := hN_var
  exact MeasureTheory.ae_eq_zero_of_integral_sq_eq_zero hN_sq_int hN_sq_zero

set_option linter.style.longLine false in
/-- Reduction from the full predictable finite-variation hypotheses to the bounded-continuous
finite-variation core.

This is the remaining analytic gap: remove predictable jumps, localize to bounded continuous
finite-variation pieces on `[⊥, t]`, prove the zero-square-integral premise by martingale
increment orthogonality along deterministic partitions, and then remove the bounded localization. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_bounded_continuous_reduction
      {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
      [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
      {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
      [IsFiniteMeasure P'] [Approximable 𝓕' P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
      {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
      (hN_cadlag : ∀ ω, IsCadlag (N · ω)) (hN_zero : ∀ ω, N ⊥ ω = 0)
      (hN_pred : IsStronglyPredictable 𝓕' N)
      (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ) {t : κ}
      (ht : (⊥ : κ) < t) :
      N t =ᵐ[P'] 0 := by
    have _hN_cadlag_used : ∀ ω, IsCadlag (N · ω) := hN_cadlag
    have _hN_zero_used : ∀ ω, N ⊥ ω = 0 := hN_zero
    have _hN_pred_used : IsStronglyPredictable 𝓕' N := hN_pred
    have _hN_var_used : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ := hN_var
    have _ht_used : (⊥ : κ) < t := ht
    have hleftLim_exists :
        ∀ ω, ∃ l, Tendsto (N · ω) (nhdsWithin t (Set.Iio t)) (nhds l) := fun ω =>
      (hN_var ω).exists_tendsto_left_univ t
    have _hleftLim_tendsto :
        ∀ ω, Tendsto (N · ω) (nhdsWithin t (Set.Iio t))
          (nhds (Function.leftLim (N · ω) t)) := fun ω =>
        tendsto_leftLim_of_tendsto (hleftLim_exists ω)
    have horthogonal_increments :
        ∀ {a b c d : κ}, a ≤ b → b ≤ c → c ≤ d →
          Integrable (fun ω => (N b ω - N a ω) * (N d ω - N c ω)) P' →
          ∫ ω, (N b ω - N a ω) * (N d ω - N c ω) ∂P' = 0 := by
      intro a b c d hab hbc hcd hprod
      exact hN.integral_increment_mul_increment_eq_zero hab hbc hcd hprod
    have _horthogonal_increments_used :
        ∀ {a b c d : κ}, a ≤ b → b ≤ c → c ≤ d →
          Integrable (fun ω => (N b ω - N a ω) * (N d ω - N c ω)) P' →
          ∫ ω, (N b ω - N a ω) * (N d ω - N c ω) ∂P' = 0 :=
      horthogonal_increments
    -- Remaining work: predictable-jump removal, bounded localization, deterministic
    -- partition construction, martingale increment orthogonality, and dominated convergence.
    sorry

/-- Bounded continuous finite-variation martingale bridge on a fixed deterministic horizon.

The deterministic square-increment estimates above close the finite-variation part of the
blueprint argument.  The remaining stochastic work is to construct the bounded continuous
localization, prove the martingale increment orthogonality identity along refining deterministic
partitions, and pass to the limit. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_bounded_continuous
      {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
      [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
      {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
      [IsFiniteMeasure P'] [Approximable 𝓕' P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
      {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
      (hN_cadlag : ∀ ω, IsCadlag (N · ω)) (hN_zero : ∀ ω, N ⊥ ω = 0)
      (hN_pred : IsStronglyPredictable 𝓕' N)
      (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ) {t : κ}
      (ht : (⊥ : κ) < t) :
      N t =ᵐ[P'] 0 := by
    exact hN.eq_zero_of_predictable_finiteVariation_bounded_continuous_reduction
      hN_cadlag hN_zero hN_pred hN_var ht

/-- Deep analytic value-zero bridge for predictable finite-variation martingales.

This is the remaining jump-removal and bounded continuous finite-variation square-increment
argument from the blueprint.  Once this fixed-time a.e. value-zero statement is available,
`eq_zero_of_predictable_finiteVariation_past_condExp_zero` follows formally by applying
conditional expectation to an a.e. zero random variable. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_value_zero
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] [Approximable 𝓕' P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
    {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    (hN_cadlag : ∀ ω, IsCadlag (N · ω)) (hN_zero : ∀ ω, N ⊥ ω = 0)
    (hN_pred : IsStronglyPredictable 𝓕' N)
    (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ) {t : κ}
    (ht : (⊥ : κ) < t) :
    N t =ᵐ[P'] 0 := by
  have _hN_cadlag_used : ∀ ω, IsCadlag (N · ω) := hN_cadlag
  have _hN_zero_used : ∀ ω, N ⊥ ω = 0 := hN_zero
  have _hN_pred_used : IsStronglyPredictable 𝓕' N := hN_pred
  have _hN_var_used : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ := hN_var
  have _ht_used : (⊥ : κ) < t := ht
  have hzero_of_past_measurable_increment :
      ∀ {s : κ}, s ≤ t → StronglyMeasurable[𝓕' s] (N t - N s) →
        N t - N s =ᵐ[P'] 0 := by
    intro s hst hmeas
    exact hN.eq_zero_of_predictable_finiteVariation_past_measurable_zero_increment hst hmeas
  have _hzero_of_past_measurable_increment :
      ∀ {s : κ}, s ≤ t → StronglyMeasurable[𝓕' s] (N t - N s) →
        N t - N s =ᵐ[P'] 0 := hzero_of_past_measurable_increment
  have hleftLim_exists :
      ∀ ω, ∃ l, Tendsto (N · ω) (nhdsWithin t (Set.Iio t)) (nhds l) := fun ω =>
    (hN_var ω).exists_tendsto_left_univ t
  have _hleftLim_tendsto :
      ∀ ω, Tendsto (N · ω) (nhdsWithin t (Set.Iio t))
        (nhds (Function.leftLim (N · ω) t)) := fun ω =>
      tendsto_leftLim_of_tendsto (hleftLim_exists ω)
  -- The remaining work is the blueprint's jump-removal plus bounded continuous
  -- finite-variation square-increment argument.
  exact hN.eq_zero_of_predictable_finiteVariation_bounded_continuous
    hN_cadlag hN_zero hN_pred hN_var ht

/-- Remaining analytic bridge: the martingale value at `t` has zero conditional expectation
against the sigma-algebra generated by all strictly earlier filtration levels.

The closed helper above reduces the case where an increment is already measurable at an earlier
filtration time to the martingale identity.  What remains here is the continuous-time limiting
argument: use left limits to remove predictable jumps, then use finite variation plus martingale
orthogonality along refining partitions to show the continuous part has zero square expectation. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_past_condExp_zero
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] [Approximable 𝓕' P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
    {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    (hN_cadlag : ∀ ω, IsCadlag (N · ω)) (hN_zero : ∀ ω, N ⊥ ω = 0)
    (hN_pred : IsStronglyPredictable 𝓕' N)
    (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ) {t : κ}
    (ht : (⊥ : κ) < t) :
    P'[N t | (⨆ s : {s : κ // s < t}, 𝓕' s)] =ᵐ[P'] 0 := by
  exact MeasureTheory.condExp_ae_eq_zero_of_ae_eq_zero
    (hN.eq_zero_of_predictable_finiteVariation_value_zero
      hN_cadlag hN_zero hN_pred hN_var ht)

/-- Analytic core of continuous-time predictable finite-variation martingale uniqueness after
the deterministic-time predictable section has been transferred to the past sigma-algebra.

The remaining proof is the jump-removal and continuous finite-variation square-increment
argument from the blueprint. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_noninitial_analytic
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] [Approximable 𝓕' P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
    {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    (hN_cadlag : ∀ ω, IsCadlag (N · ω)) (hN_zero : ∀ ω, N ⊥ ω = 0)
    (hN_pred : IsStronglyPredictable 𝓕' N)
    (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ) {t : κ}
    (ht : (⊥ : κ) < t)
    (hN_t_past : StronglyMeasurable[(⨆ s : {s : κ // s < t}, 𝓕' s)] (N t)) :
    N t =ᵐ[P'] 0 := by
  exact hN.eq_zero_of_predictable_finiteVariation_past_measurable_value hN_t_past
    (hN.eq_zero_of_predictable_finiteVariation_past_condExp_zero
      hN_cadlag hN_zero hN_pred hN_var ht)

/-- A strongly predictable càdlàg martingale with locally bounded-variation paths and zero
initial value is zero at each non-initial deterministic time, almost surely.

This is the remaining continuous-time analytic bridge in the predictable finite-variation
uniqueness route: after the discrete predictable theorem has removed sampled predictable
increments, the proof must eliminate predictable jumps and then use the continuous
finite-variation square-increment argument from the blueprint. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_noninitial
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] [Approximable 𝓕' P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
    {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    (hN_cadlag : ∀ ω, IsCadlag (N · ω)) (hN_zero : ∀ ω, N ⊥ ω = 0)
    (hN_pred : IsStronglyPredictable 𝓕' N)
    (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ) {t : κ}
    (ht : (⊥ : κ) < t) :
    N t =ᵐ[P'] 0 := by
  have hN_t_past :
    StronglyMeasurable[(⨆ s : {s : κ // s < t}, 𝓕' s)] (N t) :=
    hN_pred.stronglyMeasurable_past ht
  exact hN.eq_zero_of_predictable_finiteVariation_noninitial_analytic
    hN_cadlag hN_zero hN_pred hN_var ht hN_t_past

/-- A discrete strongly predictable martingale with zero initial value is zero at each
deterministic time, almost surely. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation_discrete
    {Ω' : Type*} {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration ℕ mΩ'}
    [IsFiniteMeasure P'] {N : ℕ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    (hN_zero : ∀ ω, N 0 ω = 0) (hN_pred : IsStronglyPredictable 𝓕' N) (n : ℕ) :
    N n =ᵐ[P'] 0 := by
  filter_upwards [hN.eq_zero_of_predictable' hN_pred n] with ω hω
  simpa [hN_zero ω] using hω

/-- A strongly predictable càdlàg martingale with locally bounded-variation paths and zero
initial value is zero at each deterministic time, almost surely. -/
lemma _root_.MeasureTheory.Martingale.eq_zero_of_predictable_finiteVariation
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] [Approximable 𝓕' P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
    {N : κ → Ω' → ℝ} (hN : Martingale N 𝓕' P')
    (hN_cadlag : ∀ ω, IsCadlag (N · ω)) (hN_zero : ∀ ω, N ⊥ ω = 0)
    (hN_pred : IsStronglyPredictable 𝓕' N)
    (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ) (t : κ) :
    N t =ᵐ[P'] 0 := by
  by_cases ht : t = ⊥
  · filter_upwards with ω
    simpa [ht] using hN_zero ω
  · have hbot : (⊥ : κ) < t := lt_of_le_of_ne bot_le (by
      intro h
      exact ht h.symm)
    exact hN.eq_zero_of_predictable_finiteVariation_noninitial hN_cadlag hN_zero hN_pred hN_var hbot

/-- A strongly predictable càdlàg local martingale with locally bounded-variation paths and
zero initial value is zero at each deterministic time, almost surely. -/
lemma IsLocalMartingale.eq_zero_of_predictable_finiteVariation
    {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
    [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
    {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {𝓕' : Filtration κ mΩ'}
    [IsFiniteMeasure P'] [Approximable 𝓕' P'] [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]
    {N : κ → Ω' → ℝ} (hN : IsLocalMartingale N 𝓕' P')
    (hN_cadlag : ∀ ω, IsCadlag (N · ω)) (hN_zero : ∀ ω, N ⊥ ω = 0)
    (hN_pred : IsStronglyPredictable 𝓕' N)
    (hN_var : ∀ ω, LocallyBoundedVariationOn (N · ω) Set.univ) (t : κ) :
    N t =ᵐ[P'] 0 := by
  have _hN_cadlag_used : ∀ ω, IsCadlag (N · ω) := hN_cadlag
  let τ : ℕ → Ω' → WithTop κ := hN.localSeq
  have hτ : IsLocalizingSequence 𝓕' τ P' := hN.isLocalizingSequence_localSeq
  have hzero_stopped : ∀ n,
      stoppedProcess (fun i ↦ {ω | ⊥ < τ n ω}.indicator (N i)) (τ n) t =ᵐ[P'] 0 := by
    intro n
    have hmart := (hN.stoppedProcess_localSeq n).1
    have hcad := (hN.stoppedProcess_localSeq n).2
    have hzero_bot :
        ∀ ω, stoppedProcess (fun i ↦ {ω | ⊥ < τ n ω}.indicator (N i)) (τ n) ⊥ ω = 0 := by
      intro ω
      by_cases hω : ⊥ < τ n ω
      · have hmem : ω ∈ {ω | ⊥ < τ n ω} := hω
        rw [stoppedProcess_eq_of_le hω.le, Set.indicator_of_mem hmem]
        exact hN_zero ω
      · simp [stoppedProcess, hω]
    have hpred :
        IsStronglyPredictable 𝓕'
          (stoppedProcess (fun i ↦ {ω | ⊥ < τ n ω}.indicator (N i)) (τ n)) :=
      hN_pred.stoppedProcess_indicator (hτ.isStoppingTime n)
    have hvar : ∀ ω,
        LocallyBoundedVariationOn
          ((stoppedProcess (fun i ↦ {ω | ⊥ < τ n ω}.indicator (N i)) (τ n)) · ω)
          Set.univ := by
      intro ω
      exact locallyBoundedVariationOn_stoppedProcess_indicator hN_var ω
    exact hmart.eq_zero_of_predictable_finiteVariation hcad hzero_bot hpred hvar t
  have hall_zero : ∀ᵐ ω ∂P', ∀ n,
      stoppedProcess (fun i ↦ {ω | ⊥ < τ n ω}.indicator (N i)) (τ n) t ω = 0 := by
    exact ae_all_iff.2 hzero_stopped
  filter_upwards [hτ.tendsto_top, hall_zero] with ω htop hzeros
  simp only [tendsto_atTop_nhds] at htop
  obtain ⟨n, hn⟩ := htop (Set.Ioi (t : WithTop κ)) (by simp) isOpen_Ioi
  have htτ : (t : WithTop κ) < τ n ω := hn n le_rfl
  have hbotτ : (⊥ : κ) < τ n ω :=
    lt_of_le_of_lt (WithTop.coe_le_coe.2 bot_le) htτ
  have hmem : ω ∈ {ω | ⊥ < τ n ω} := hbotτ
  have hstop_eq :
      stoppedProcess (fun i ↦ {ω | ⊥ < τ n ω}.indicator (N i)) (τ n) t ω = N t ω := by
    rw [stoppedProcess_eq_of_le htτ.le, Set.indicator_of_mem hmem]
  exact hstop_eq ▸ hzeros n

namespace IsLocalSubmartingale

theorem doob_meyer (hX : IsLocalSubmartingale X 𝓕 P) (hX_cadlag : ∀ ω, IsCadlag (X · ω)) :
    ∃ (M A : ι → Ω → ℝ), X = M + A ∧ IsLocalMartingale M 𝓕 P ∧ (∀ ω, IsCadlag (M · ω)) ∧
      IsStronglyPredictable 𝓕 A ∧ IsStronglyProgressive 𝓕 A ∧
      (∀ ω, IsCadlag (A · ω)) ∧ (HasLocallyIntegrableSup A 𝓕 P) ∧
      (∀ ω, Monotone (A · ω)) := by
  sorry

section Normalized

variable {κ Ω' : Type*} [ConditionallyCompleteLinearOrderBot κ] [TopologicalSpace κ]
  [OrderTopology κ] [MeasurableSpace κ] [BorelSpace κ] [PolishSpace κ]
  {mΩ' : MeasurableSpace Ω'} {P' : Measure Ω'} {X' : κ → Ω' → ℝ}
  {𝓕' : Filtration κ mΩ'} [IsFiniteMeasure P'] [Approximable 𝓕' P']
  [𝓕'.IsComplete P'] [𝓕'.IsRightContinuous]

/-- A normalized local Doob-Meyer decomposition whose predictable part starts from zero. -/
theorem doob_meyer_normalized (hX : IsLocalSubmartingale X' 𝓕' P')
    (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    ∃ (M A : κ → Ω' → ℝ), X' = M + A ∧ IsLocalMartingale M 𝓕' P' ∧
      (∀ ω, IsCadlag (M · ω)) ∧ IsStronglyPredictable 𝓕' A ∧
      IsStronglyProgressive 𝓕' A ∧ (∀ ω, IsCadlag (A · ω)) ∧
      HasLocallyIntegrableSup A 𝓕' P' ∧ (∀ ω, Monotone (A · ω)) ∧
      (∀ ω, A ⊥ ω = 0) := by
  classical
  rcases hX.doob_meyer hX_cadlag with
    ⟨M, A, hXA, hM, hM_cadlag, hA_pred, hA_prog, hA_cadlag, hA_int, hA_mono⟩
  let C : κ → Ω' → ℝ := fun _ ω => A ⊥ ω
  have hC_pred : IsStronglyPredictable 𝓕' C := by
    exact MeasureTheory.IsStronglyPredictable.const_fun (𝓕 := 𝓕')
      (hA_prog.stronglyAdapted ⊥)
  have hC_prog : IsStronglyProgressive 𝓕' C := by
    intro i
    exact ((hA_prog.stronglyAdapted ⊥).mono (𝓕'.mono bot_le)).comp_measurable measurable_snd
  have hC_cadlag : ∀ ω, IsCadlag (C · ω) := by
    intro ω
    exact (continuous_const : Continuous fun _ : κ => A ⊥ ω).isCadlag
  refine ⟨M + C, A - C, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · ext t ω
    rw [hXA]
    simp only [Pi.add_apply, Pi.sub_apply, C]
    ring
  · -- Simultaneous localization makes the initial-value shift a local martingale.
    exact hM.add_initial_of_hasLocallyIntegrableSup hA_prog hA_int
  · intro ω
    exact (hM_cadlag ω).add (hC_cadlag ω)
  · simpa only [Pi.sub_apply] using hA_pred.sub hC_pred
  · simpa only [Pi.sub_apply] using hA_prog.sub hC_prog
  · intro ω
    have hnegC : IsCadlag fun t : κ => (-1 : ℝ) • C t ω := (hC_cadlag ω).const_smul (-1)
    have hadd : IsCadlag ((fun t : κ => A t ω) + fun t => (-1 : ℝ) • C t ω) :=
      (hA_cadlag ω).add hnegC
    simpa [sub_eq_add_neg, C] using hadd
  · -- The locally integrable running supremum is stable under the normalization shift.
    exact hA_int.sub_initial hA_prog
  · intro ω i j hij
    exact sub_le_sub_right (hA_mono ω hij) (A ⊥ ω)
  · intro ω
    simp [C]

/-- The local martingale part of the Doob-Meyer decomposition of the local submartingale. -/
noncomputable
def martingalePart (X : κ → Ω' → ℝ)
    (hX : IsLocalSubmartingale X 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X · ω)) :
    κ → Ω' → ℝ :=
  (hX.doob_meyer_normalized hX_cadlag).choose

/-- The predictable part of the Doob-Meyer decomposition of the local submartingale. -/
noncomputable
def predictablePart (X : κ → Ω' → ℝ)
    (hX : IsLocalSubmartingale X 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X · ω)) :
    κ → Ω' → ℝ :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose

lemma martingalePart_add_predictablePart
    (hX : IsLocalSubmartingale X' 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    X' = hX.martingalePart X' hX_cadlag + hX.predictablePart X' hX_cadlag :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.1

lemma isLocalMartingale_martingalePart
    (hX : IsLocalSubmartingale X' 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    IsLocalMartingale (hX.martingalePart X' hX_cadlag) 𝓕' P' :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.2.1

lemma cadlag_martingalePart
    (hX : IsLocalSubmartingale X' 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    ∀ ω, IsCadlag (hX.martingalePart X' hX_cadlag · ω) :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.2.2.1

lemma isStronglyProgressive_predictablePart
    (hX : IsLocalSubmartingale X' 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    IsStronglyProgressive 𝓕' (hX.predictablePart X' hX_cadlag) :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.2.2.2.2.1

lemma isStronglyPredictable_predictablePart
    (hX : IsLocalSubmartingale X' 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    IsStronglyPredictable 𝓕' (hX.predictablePart X' hX_cadlag) :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.2.2.2.1

lemma cadlag_predictablePart
    (hX : IsLocalSubmartingale X' 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    ∀ ω, IsCadlag (hX.predictablePart X' hX_cadlag · ω) :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.2.2.2.2.2.1

lemma hasLocallyIntegrableSup_predictablePart
    (hX : IsLocalSubmartingale X' 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    HasLocallyIntegrableSup (hX.predictablePart X' hX_cadlag) 𝓕' P' :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.2.2.2.2.2.2.1

lemma monotone_predictablePart (hX : IsLocalSubmartingale X' 𝓕' P')
    (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    ∀ ω, Monotone (hX.predictablePart X' hX_cadlag · ω) :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.2.2.2.2.2.2.2.1

lemma predictablePart_bot_eq_zero (hX : IsLocalSubmartingale X' 𝓕' P')
    (hX_cadlag : ∀ ω, IsCadlag (X' · ω)) :
    ∀ ω, hX.predictablePart X' hX_cadlag ⊥ ω = 0 :=
  (hX.doob_meyer_normalized hX_cadlag).choose_spec.choose_spec.2.2.2.2.2.2.2.2

/-- Any normalized Doob-Meyer decomposition has the same predictable part as the choice-based
normalized decomposition, at each deterministic time and almost surely. -/
lemma predictablePart_eq_of_normalized_decomposition
    (hX : IsLocalSubmartingale X' 𝓕' P') (hX_cadlag : ∀ ω, IsCadlag (X' · ω))
    {M A : κ → Ω' → ℝ} (hXA : X' = M + A)
    (hM : IsLocalMartingale M 𝓕' P') (hM_cadlag : ∀ ω, IsCadlag (M · ω))
    (hA_pred : IsStronglyPredictable 𝓕' A) (hA_prog : IsStronglyProgressive 𝓕' A)
    (hA_cadlag : ∀ ω, IsCadlag (A · ω))
    (hA_int : HasLocallyIntegrableSup A 𝓕' P') (hA_mono : ∀ ω, Monotone (A · ω))
    (hA_zero : ∀ ω, A ⊥ ω = 0) (t : κ) :
    hX.predictablePart X' hX_cadlag t =ᵐ[P'] A t := by
  let M0 : κ → Ω' → ℝ := hX.martingalePart X' hX_cadlag
  let A0 : κ → Ω' → ℝ := hX.predictablePart X' hX_cadlag
  have _hM_cadlag_used := hM_cadlag
  have _hA_prog_used := hA_prog
  have _hA_int_used := hA_int
  have hchosen : X' = M0 + A0 := by
    simpa [M0, A0] using hX.martingalePart_add_predictablePart hX_cadlag
  have hA0_eq : A0 - A = M - M0 := by
    ext s ω
    have hsum := congr_fun (congr_fun (hchosen.symm.trans hXA) s) ω
    simp only [Pi.add_apply] at hsum
    simp only [Pi.sub_apply]
    linarith
  have hN_mart : IsLocalMartingale (A0 - A) 𝓕' P' := by
    rw [hA0_eq]
    have hM0 : IsLocalMartingale M0 𝓕' P' := by
      simpa [M0] using hX.isLocalMartingale_martingalePart hX_cadlag
    exact hM.sub hM0
  have hN_cadlag : ∀ ω, IsCadlag ((A0 - A) · ω) := by
    intro ω
    have hA0_cad : IsCadlag (A0 · ω) := by
      simpa [A0] using hX.cadlag_predictablePart hX_cadlag ω
    have hneg : IsCadlag (fun s : κ => (-1 : ℝ) • A s ω) :=
      (hA_cadlag ω).const_smul (-1)
    have hadd :
        IsCadlag ((fun s : κ => A0 s ω) + fun s => (-1 : ℝ) • A s ω) :=
      hA0_cad.add hneg
    simpa [Pi.sub_apply, sub_eq_add_neg] using hadd
  have hN_zero : ∀ ω, (A0 - A) ⊥ ω = 0 := by
    intro ω
    simp [A0, hX.predictablePart_bot_eq_zero hX_cadlag ω, hA_zero ω]
  have hN_pred : IsStronglyPredictable 𝓕' (A0 - A) := by
    have hA0_pred : IsStronglyPredictable 𝓕' A0 := by
      simpa [A0] using hX.isStronglyPredictable_predictablePart hX_cadlag
    exact hA0_pred.sub hA_pred
  have hN_var : ∀ ω, LocallyBoundedVariationOn ((A0 - A) · ω) Set.univ := by
    intro ω
    have hA0_mono : Monotone (A0 · ω) := by
      simpa [A0] using hX.monotone_predictablePart hX_cadlag ω
    have hA0_monoOn : MonotoneOn (A0 · ω) Set.univ :=
      fun _ _ _ _ hst => hA0_mono hst
    have hA_monoOn : MonotoneOn (A · ω) Set.univ :=
      fun _ _ _ _ hst => hA_mono ω hst
    exact hA0_monoOn.locallyBoundedVariationOn.sub
      hA_monoOn.locallyBoundedVariationOn
  have hzero :=
    hN_mart.eq_zero_of_predictable_finiteVariation hN_cadlag hN_zero hN_pred hN_var t
  filter_upwards [hzero] with ω hω
  have hdiff : A0 t ω - A t ω = 0 := by
    simpa [A0, Pi.sub_apply] using hω
  change A0 t ω = A t ω
  linarith

end Normalized

end IsLocalSubmartingale

end ProbabilityTheory
