import KolmogorovExtension4.KolmogorovExtension
import Mathlib.MeasureTheory.Measure.CharacteristicFunction
import Mathlib.Probability.Distributions.Gaussian.Basic
import Mathlib.Probability.Moments.CovarianceBilin
